package com.hsm.html;

import lombok.Getter;

/**
 * @Classname HtmlTransferEnum
 * @Description TODO
 * @Date 2021/9/1 18:14
 * @Created by huangsm
 */
@Getter
public enum HtmlTransferEnum {
    Alpha("Α","&Alpha;","&#913;"),
    Delta("Δ","&Delta;","&#916;"),
    Eta("Η","&Eta;","&#919;"),
    Kappa("Κ","&Kappa;","&#922;"),
    Nu("Ν","&Nu;","&#925;"),
    Pi("Π","&Pi;","&#928;"),
    Tau("Τ","&Tau;","&#932;"),
    Chi("Χ","&Chi;","&#935;"),
    alpha("α","&alpha;","&#945;"),
    delta("δ","&delta;","&#948;"),
    eta("η","&eta;","&#951;"),
    kappa("κ","&kappa;","&#954;"),
    nu("ν","&nu;","&#957;"),
    pi("π","&pi;","&#960;"),
    sigma("σ","&sigma;","&#963;"),
    phi("φ","&phi;","&#966;"),
    omega("ω","&omega;","&#969;"),
    piv("ϖ","&piv;","&#982;"),
    prime("′","&prime;","&#8242;"),
    frasl("⁄","&frasl;","&#8260;"),
    real("ℜ","&real;","&#8476;"),
    larr("←","&larr;","&#8592;"),
    darr("↓","&darr;","&#8595;"),
    lArr("⇐","&lArr;","&#8656;"),
    dArr("⇓","&dArr;","&#8659;"),
    part("∂","&part;","&#8706;"),
    nabla("∇","&nabla;","&#8711;"),
    ni("∋","&ni;","&#8715;"),
    minus("−","&minus;","&#8722;"),
    prop("∝","&prop;","&#8733;"),
    and("∧","&and;","&#8869;"),
    cup("∪","&cup;","&#8746;"),
    sim("∼","&sim;","&#8764;"),
    ne("≠","&ne;","&#8800;"),
    ge("≥","&ge;","&#8805;"),
    nsub("⊄","&nsub;","&#8836;"),
    oplus("⊕","&oplus;","&#8853;"),
    sdot("⋅","&sdot;","&#8901;"),
    lfloor("⌊","&lfloor;","&#8970;"),
    spades("♠","&spades;","&#9824;"),
    diams("♦","&diams;","&#9830;"),
    cent("¢","&cent;","&#162;"),
    yen("¥","&yen;","&#165;"),
    uml("¨","&uml;","&#168;"),
    laquo("«","&laquo;","&#171;"),
    reg("®","&reg;","&#174;"),
    plusmn("±","&plusmn;","&#177;"),
    acute("´","&acute;","&#180;"),
    lt("<","&lt;","&#60;"),
    Beta("Β","&Beta;","&#914;"),
    Epsilon("Ε","&Epsilon;","&#917;"),
    Theta("Θ","&Theta;","&#920;"),
    Lambda("A","&Lambda;","&#923;"),
    Xi("Ξ","&Xi;","&#926;"),
    Rho("Ρ","&Rho;","&#929;"),
    Upsilon("Υ","&Upsilon;","&#933;"),
    Psi("Ψ","&Psi;","&#936;"),
    beta("β","&beta;","&#946;"),
    epsilon("ε","&epsilon;","&#949;"),
    theta("θ","&theta;","&#952;"),
    lambda("λ","&lambda;","&#955;"),
    xi("ξ","&xi;","&#958;"),
    rho("ρ","&rho;","&#961;"),
    tau("τ","&tau;","&#964;"),
    chi("χ","&chi;","&#967;"),
    thetasym("ϑ","&thetasym;","&#977;"),
    bull("•","&bull;","&#8226;"),
    Prime("″","&Prime;","&#8243;"),
    weierp("℘","&weierp;","&#8472;"),
    trade("™","&trade;","&#8482;"),
    uarr("↑","&uarr;","&#8593;"),
    harr("↔","&harr;","&#8596;"),
    uArr("⇑","&uArr;","&#8657;"),
    hArr("⇔","&hArr;","&#8660;"),
    exist("∃","&exist;","&#8707;"),
    isin("∈","&isin;","&#8712;"),
    prod("∏","&prod;","&#8719;"),
    lowast("∗","&lowast;","&#8727;"),
    infin("∞","&infin;","&#8734;"),
    or("∨","&or;","&#8870;"),
    int_("∫","&int;","&#8747;"),
    cong("≅","&cong;","&#8773;"),
    equiv("≡","&equiv;","&#8801;"),
    sub("⊂","&sub;","&#8834;"),
    sube("⊆","&sube;","&#8838;"),
    otimes("⊗","&otimes;","&#8855;"),
    lceil("⌈","&lceil;","&#8968;"),
    rfloor("⌋","&rfloor;","&#8971;"),
    clubs("♣","&clubs;","&#9827;"),
    nbsp(" ","&nbsp;","&#160;"),
    pound("£","&pound;","&#163;"),
    brvbar("¦","&brvbar;","&#166;"),
    copy("©","&copy;","&#169;"),
    not("¬","&not;","&#172;"),
    macr("¯","&macr;","&#175;"),
    sup2("²","&sup2;","&#178;"),
    micro("µ","&micro;","&#181"),
    gt(">","&gt;","&#62;"),
    Gamma("Γ","&Gamma;","&#915;"),
    Zeta("Ζ","&Zeta;","&#918;"),
    Iota("Ι","&Iota;","&#921;"),
    Mu("Μ","&Mu;","&#924;"),
    Omicron("Ο","&Omicron;","&#927;"),
    Sigma("Σ","&Sigma;","&#931;"),
    Phi("Φ","&Phi;","&#934;"),
    Omega("Ω","&Omega;","&#937;"),
    gamma("γ","&gamma;","&#947;"),
    zeta("ζ","&zeta;","&#950;"),
    iota("ι","&iota;","&#953;"),
    mu("μ","&mu;","&#956;"),
    omicron("ο","&omicron;","&#959;"),
    sigmaf("ς","&sigmaf;","&#962;"),
    upsilon("υ","&upsilon;","&#965;"),
    psi("ψ","&psi;","&#968;"),
    upsih("ϒ","&upsih;","&#978;"),
    hellip("…","&hellip;","&#8230;"),
    oline("‾","&oline;","&#8254;"),
    image("ℑ","&image;","&#8465;"),
    alefsym("ℵ","&alefsym;","&#8501;"),
    rarr("→","&rarr;","&#8594;"),
    crarr("↵","&crarr;","&#8629;"),
    rArr("⇒","&rArr;","&#8658;"),
    forall("∀","&forall;","&#8704;"),
    empty("∅","&empty;","&#8709;"),
    notin("∉","&notin;","&#8713;"),
    sum("∑","&sum;","&#8722;"),
    radic("√","&radic;","&#8730;"),
    ang("∠","&ang;","&#8736;"),
    cap("∩","&cap;","&#8745;"),
    there4("∴","&there4;","&#8756;"),
    asymp("≈","&asymp;","&#8773;"),
    le("≤","&le;","&#8804;"),
    sup("⊃","&sup;","&#8835;"),
    supe("⊇","&supe;","&#8839;"),
    perp("⊥","&perp;","&#8869;"),
    rceil("⌉","&rceil;","&#8969;"),
    loz("◊","&loz;","&#9674;"),
    hearts("♥","&hearts;","&#9829;"),
    iexcl("¡","&iexcl;","&#161;"),
    curren("¤","&curren;","&#164;"),
    sect("§","&sect;","&#167;"),
    ordf("ª","&ordf;","&#170;"),
    shy("","&shy;","&#173;"),
    deg("°","&deg;","&#176;"),
    sup3("³","&sup3;","&#179;"),
    quot("\"","&quot;","&#34;"),
    _39("\'","\'","&#39;"),
    ldquo("“","&ldquo;","”"),
    rdquo("”","&rdquo;","”"),
    apos("'","&apos;","&#39;"),
    amp("&","&amp;","&#38;"),
    raquo("»","&raquo;","&#187;"),
    times("×","&times;","&#215;"),
    para("¶","&para;","&#182;"),
    middot("·","&middot;","&#183;"),
    cedil("¸","&cedil;","&#184;"),
    sup1("¹","&sup1;","&#185;"),
    ordm("º","&ordm;","&#186;"),
    frac14("¼","&frac14;","&#188;"),
    frac12("½","&frac12;","&#189;"),
    frac34("¾","&frac34;","&#190;"),
    iquest("¿","&iquest;","&#191;"),
    divide("÷","&divide;","&#247;"),
    exists("∃","&exists;","&#8707;"),
    OElig("Œ","&OElig;","&#338;"),
    oelig("œ","&oelig;","&#339;"),
    Scaron("Š","&Scaron;","&#352;"),
    scaron("š","&scaron;","&#353;"),
    Yuml("Ÿ","&Yuml;","&#376;"),
    fnof("ƒ","&fnof;","&#402;"),
    circ("ˆ","&circ;","&#710;"),
    tilde("˜","&tilde;","&#732;"),
    ndash("–","&ndash;","&#8211;"),
    mdash("—","&mdash;","&#8212;"),
    lsquo("‘","&lsquo;","&#8216;"),
    rsquo("’","&rsquo;","&#8217;"),
    sbquo("‚","&sbquo;","&#8218;"),
    bdquo("„","&bdquo;","&#8222;"),
    dagger("†","&dagger;","&#8224;"),
    Dagger("‡","&Dagger;","&#8225;"),
    permil("‰","&permil;","&#8240;"),
    lsaquo("‹","&lsaquo;","&#8249;"),
    rsaquo("›","&rsaquo;","&#8250;"),
    euro("€","&euro;","&#8364;"),
    ;

    /**
     * 展示效果
     */
    private String show;
    /**
     * 实体命名
     */
    private String name;

    /**
     * 十进制命名
     */
    private String tenName;

    HtmlTransferEnum(String show, String name, String tenName) {
        this.show = show;
        this.name = name;
        this.tenName = tenName;
    }

    public static String replaceAllTrans(String htmlStr){
        for (HtmlTransferEnum value : HtmlTransferEnum.values()) {
            htmlStr = htmlStr.replaceAll(value.getName(),value.getShow())
                    .replaceAll(value.getTenName(),value.getShow());
        }
        return htmlStr;
    }
}
